# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17c9657a05843144dc752da30ce41a74e4bb1e84b1f2a36ba4b1fd80c16d5b078a8a46f742492394980b6a3ce24cff07c2d6958d2f29dd4773283f361aa23aa2

test:
  secret_key_base: ba2bfb790937fc40dfe59679ac29df243425ef8497a79b890fa3944cb8f98370351306114e00d6a309be8845541f4f33167d7641d72ce8487d70b8ae36cf033f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
